### ISSUE TITLE
Utiliser le HEVC comme format hd et sd

### ISSUE THREAD

**Issue by cocof35** [dreamvids/DreamVids#107]
Le codec hevc permet de diminuer le debit necessaire a la lecture par 2, ce qui peut permettre a des gens ayant une mauvaise connexion de profiter plus facillement d'une video hd

**Comment by BrezhDev** [comment]
Est-il compatible avec les navigateur actuel ?

cocof35 <notifications@github.com> a écrit :

**Comment by cocof35** [comment]
Il peut etre intégrer facilement grace a librairie libde265.js (http://www.libde265.org) en considérent que le player du site est en html5. La librairie libde265.js rend donc tous les navigateur compatible avec le codec

**Comment by cocof35** [comment]
FFMPEG permet de convertir les video dans ce format et comme c'est la librairie utiliser par le site pour convertir les video...

**Comment by BrezhDev** [comment]
Merci, nous allons nous pencher dessus dans ce cas.
Êtes vous développer de ce codec ou utilisateur occasionnel ?

cocof35 <notifications@github.com> a écrit :

**Comment by cocof35** [comment]
plutot utilisateur mais en l'utilisant avec des film sur vlc, j'ai vu la difference
