### ISSUE TITLE
Support docker

### ISSUE THREAD

**Issue by MikaXII** [dreamvids/DreamVids#120]
J'ai vu que vous êtes en refonte complète (courage les gars)
Du coup l'ajout d'un docker officiel pourrait être pas mal non ? 
(J'utilise rancher et du coup pour des déploiement d'applications c'est un tuerie)

**Comment by quadrifoglio** [comment]
C'est prévu, en tout cas pour une version dev, nous ne sommes pas sûr d'utiliser Docker en production.
