### ISSUE TITLE
dead website and poor docs

### ISSUE THREAD

**Issue by aolko** [dreamvids/DreamVids#125]
Are you going to make a decent website and docs?

**Comment by aolko** [comment]
still dead

**Comment by lunarfolk** [comment]
It looks like their domain name has not been renewed, the whois record has been updated recently and shows that the domain is now owned by a domain broker... Definitly dead.

**Comment by sundowndev** [comment]
You might be looking for this very similar and recent project https://github.com/Dreamvo

**Comment by aolko** [comment]
![](https://i.imgur.com/rdRZXNv.png)
nice
and the main repo is empty

**Comment by sundowndev** [comment]
*"very recent"* also if you're a developer you can still contribute, just send a mail to *raphael@crvx.fr*
