### ISSUE TITLE
Style de card nouvelle pour les vidéos publiés dans le flux d'activité

### ISSUE THREAD

**Issue by dimitrinicolas** [dreamvids/DreamVids#83]
La vue `feed/feed.php` rends toute les cards non vues avec une classe `card-new` supplémentaire pour afficher un background orange sauf pour les cards videos qui sont générés par la fonction`Utils::getVideoCardHTML` qui ne sait pas s'il faut ajouter la classe `card-new` ou pas.

@Snapcube @Vetiore

**Comment by Snapcube** [comment]
Ah ouais faut voir ca

**Comment by Snapcube** [comment]
Fixed
